services:
  postgres:
    image: postgres:15-alpine
    container_name: wdh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wdh_user
      POSTGRES_PASSWORD: wdh_password
      POSTGRES_DB: wdh_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wdh-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wdh-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://wdh_user:wdh_password@postgres:5432/wdh_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - wdh-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wdh-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wdh-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
    driver: local

networks:
  wdh-network:
    driver: bridge
